artifacts: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  raw_data_dir: raw
  ingested_data_dir: ingested_data
  download_url: ""

data_preprocessing:
  root_dir: artifacts/data_preprocessing
  dataset: tweet_data.csv

feature_engineering:
  root_dir: artifacts/feature_engineering
  models_dir: artifacts/models
  preprocessed_dataset: clean_data.csv 

model_training:
  models_dir: artifacts/models
  model_name: XgBoost-test1
  train_dataset: train_data.csv

model_evaluation:
  models_dir: artifacts/models
  test_dataset: test_data.csv
  reports_dir: reports
  evaluation_report: evaluation_report.json
  experiment_info: experiment_info.json

model_registration:
  experiment_info: experiment_info.json