artifacts: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  raw_data_dir: raw
  ingested_data_dir: ingested_data
  download_url: ""

data_preprocessing:
  root_dir: artifacts/data_preprocessing
  dataset: tweet_data.csv

feature_engineering:
  root_dir: artifacts/feature_engineering
  models_dir: artifacts/models
  preprocessed_dataset: clean_data.csv 

model_training:
  models_dir: artifacts/models
  train_dataset: train_data.csv
  test_dataset: test_data.csv