aretfacts: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  raw_data_dir: raw
  ingested_data_dir: ingested_data
  download_url: https://raw.githubusercontent.com/SubinoyBera/Project-Datasets/main/Toxic-TweetTagger-dataset.zip

data_preprocessing:
  root_dir: artifacts/data_preprocessing
  dataset: tweet_data.csv

feature_engineering:
  root_dir: artifacts/feature_engineering
  models_dir: models
  preprocessed_dataset: clean_data.feather

model_training:
  models_dir: models
  train_dataset: train_data.feather

model_evaluation:
  test_dataset: test_data.feather
  reports_dir: reports
  evaluation_report: metrics.json
  experiment_info: experiment.json

model_registration:
  experiment_info: experiment.json