stages:
  data_ingestion:
    cmd: python -m src.components.data_ingestion
    deps:
      - src/components/data_ingestion.py
      - src/core/configuration.py
    outs:
      - artifacts/data_ingestion/raw/tweet_data.csv
      - artifacts/data_ingestion/train_data.parquet
      - artifacts/data_ingestion/test_data.parquet

  data_validation:
    cmd: python -m src.components.data_validation
    deps:
      - src/components/data_validation.py
      - src/core/configuration.py
      - artifacts/data_ingestion
    outs:
      - artifacts/data_validation/validation_status.txt
      - reports/data_drift.json

  data_preprocessing:
    cmd: python -m src.components.data_preprocessing
    deps:
      - src/components/data_preprocessing.py
      - src/core/configuration.py
      - artifacts/data_ingestion/train_data.parquet
      - artifacts/data_validation/validation_status.txt
    outs:
      - artifacts/data_preprocessing/preprocessed_train_data.feather

  feature_engineering:
    cmd: python -m src.components.feature_engineering
    deps:
      - src/components/feature_engineering.py
      - src/core/configuration.py
      - artifacts/data_preprocessing
    params:
      - feature_engineering.max_features
    outs:
      - models/vectorizer_meta.txt
      - artifacts/feature_engineering/train_data.feather

  model_training:
    cmd: python -m src.components.model_training
    deps:
      - src/components/model_training.py
      - src/core/configuration.py
      - artifacts/feature_engineering/train_data.feather
    params:
      - model_training.hyperparameters
    outs:
      - models/model_meta.txt

  model_evaluation:
    cmd: python -m src.components.model_evaluation
    deps:
      - src/components/model_evaluation.py
      - src/components/data_preprocessing.py
      - src/script/model_wrapper.py
      - src/core/configuration.py
      - artifacts/data_ingestion/test_data.parquet
      - models/model_meta.txt
    params:
      - model_training.model_name
    outs:
      - reports/metrics.json
      - reports/experiment.json

  model_registration:
    cmd: python -m src.operations.register_model
    deps:
      - src/operations/register_model.py
      - src/core/configuration.py
      - reports/experiment.json
