feature_engineering:
  vectorizer: Tfidf
  max_features: 500
  min_df: 3
  ngrams:
    min: 1
    max: 1

model_training:
  model_name: XGB-test01
  hyperparameters:
    n_estimators: 100
    learning_rate: 0.1
    max_depth: 5
    gamma: 0.1
    reg_lambda: 0