feature_engineering:
  vectorizer: TfidfVectorizer
  max_features: 3000
  min_df: 3
  ngrams:
    min: 1
    max: 1

model_training:
  model_name: XGB-v1
  hyperparametrs:
    n_estimators: 1000
    learning_rate: 0.1
    max_depth: 12 
    gamma: 0.1
    reg_lambda: 1
    subsample: 0.8
    random_state: 42